language: ruby
sudo: true
cache: bundler
rvm:
  - 2.3.1
before_install:
  - "sudo apt-get install xvfb"
  - "sudo apt-get install vim-gtk"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "vim --version"
