---
language: minimal
dist: trusty
sudo: required
notifications:
  email: false

before_install:
  - git clone https://github.com/junegunn/vader.vim.git ~/.vim/plugged/vader.vim
  - git clone https://github.com/vim/vim
  - rvm use system

install:
  - >
    (cd vim ; ./configure
    --with-features=huge
    --enable-rubyinterp
    --enable-pythoninterp)
  - make -C ./vim -j4
  - sudo make -C ./vim install

before_script:
  - export PATH="/usr/local/bin:${PATH}"

jobs:
  include:
    - stage: test
      name: "Aliases"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/alias-spec.vader' > /dev/null
    - stage: test
      name: "Expressions"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/expression-spec.vader' > /dev/null
    - stage: test
      name: "Fields"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/fields-spec.vader' > /dev/null
    - stage: test
      name: "Indents"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/indent-spec.vader' > /dev/null
    - stage: test
      name: "Symbols"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/symbol-spec.vader' > /dev/null
...
