---
language: vim

before_script:
  - 'git clone https://github.com/vim/vim'
  - 'pushd vim'
  - './configure'
    '--with-features=huge'
    '--enable-rubyinterp'
    '--enable-pythoninterp'
  - 'make -j4'
  - 'sudo make install'
  - 'popd'
  - 'git clone https://github.com/junegunn/vader.vim.git'

script:
  - 'export PATH="/usr/local/bin:$PATH"'
  - "vim -Nu test/vimrc-test -c 'Vader! test/*.vader' > /dev/null"
...
