---
language: minimal
dist: trusty
sudo: required
notifications:
  email: false

before_install:
  - git clone https://github.com/junegunn/vader.vim.git ~/.vim/plugged/vader.vim
  - git clone https://github.com/vim/vim
  - rvm use system

install:
  - >
    (cd vim ; ./configure
    --with-features=huge
    --enable-rubyinterp
    --enable-pythoninterp)
  - make -C ./vim -j4
  - sudo make -C ./vim install

before_script:
  - export PATH="/usr/local/bin:${PATH}"

jobs:
  include:
    - stage: test
      name: "Bracket: Aliases"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/alias-spec.vader' > /dev/null
    - stage: test

      name: "Bracket: Expressions: General"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/expression-general-spec.vader' > /dev/null
    - stage: test
      name: "Bracket: Expressions: Whitespace"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/expression-whitespace-spec.vader' > /dev/null
    - stage: test
      name: "Bracket: Expressions: Nested"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/expression-nested-spec.vader' > /dev/null
    - stage: test
      name: "Bracket: Expressions: Multiline: Trailing"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/expression-multiline-trailing-spec.vader' > /dev/null
    - stage: test
      name: "Bracket: Expressions: Multiline: Leading"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/expression-multiline-leading-spec.vader' > /dev/null
    - stage: test
      name: "Bracket: Expressions: Multiline: Indented"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/expression-multiline-indented-spec.vader' > /dev/null
    - stage: test

      name: "Bracket: Fields: Short: if"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/field-short-if-spec.vader' > /dev/null
    - stage: test
      name: "Bracket: Fields: Short: af"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/field-short-af-spec.vader' > /dev/null

    - stage: test
      name: "Bracket: Fields: Trailing: if"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/field-trailing-if-spec.vader' > /dev/null
    - stage: test
      name: "Bracket: Fields: Trailing: af"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/field-trailing-af-spec.vader' > /dev/null

    - stage: test
      name: "Bracket: Fields: Indented: if"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/field-indented-if-spec.vader' > /dev/null
    - stage: test
      name: "Bracket: Fields: Indented: af"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/field-indented-af-spec.vader' > /dev/null
    - stage: test

      name: "Bracket: Fields: Leading: if"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/field-leading-if-spec.vader' > /dev/null
    - stage: test
      name: "Bracket: Fields: Leading: af"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/field-leading-af-spec.vader' > /dev/null
    - stage: test

      name: "Other: Indents"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/other/indent-spec.vader' > /dev/null
    - stage: test
      name: "Other: Symbols"
      script: vim -u 'test/vimrc-test.vim' -c 'Vader! test/other/symbol-spec.vader' > /dev/null
...
