language: ruby
before_script:
  - git clone https://github.com/junegunn/vader.vim.git
  - git clone https://github.com/vim/vim
  - cd vim
  - ./configure --with-features=huge --enable-rubyinterp --enable-pythoninterp
  - make -j4
  - sudo make install
  - cd -

script: 
  - export PATH="/usr/local/bin:$PATH"
  - export LD_LIBRARY_PATH=~/.rvm/rubies/ruby-2.2.3/lib
  - vim -Nu <(cat << VIMRC
  set nocompatible
  filetype off
  set rtp+=vader.vim
  set rtp+=.
  filetype plugin indent on
  syntax enable
  VIMRC) vim -c ':set t_ti= t_te= nomore' -c 'set rtp? | q!'
  - vim -Nu <(cat << VIMRC
  set nocompatible
  filetype off
  set rtp+=vader.vim
  set rtp+=.
  filetype plugin indent on
  syntax enable
  VIMRC) -c ':set t_ti= t_te= nomore' -c 'scriptnames | q!'

  - vim -Nu <(cat << VIMRC
  set nocompatible
  filetype off
  set rtp+=vader.vim
  set rtp+=.
  filetype plugin indent on
  syntax enable
  VIMRC) -c 'Vader! test/*' > /dev/null
