---
language: minimal
dist: trusty
sudo: required
notifications:
  email: false

before_install:
  - git clone https://github.com/junegunn/vader.vim.git ~/.vim/plugged/vader.vim
  - git clone https://github.com/neovim/neovim.git
  - rvm use system

install:
  - (cd neovim ; make CMAKE_BUILD_TYPE=Release; sudo make install)

before_script:
  - export PATH="/usr/local/bin:${PATH}"

env:
  matrix:
    - TARGET='alias'

    - TARGET='expression-count-if'
    - TARGET='expression-count-af'
    - TARGET='expression-general-if'
    - TARGET='expression-general-af'

    - TARGET='expression-multiline-indented'
    - TARGET='expression-multiline-leading'
    - TARGET='expression-multiline-trailing'

    - TARGET='expression-nested'
    - TARGET='expression-nestedfurther'

    - TARGET='expression-repeated'
    - TARGET='expression-unreachable'
    - TARGET='expression-whitespace'

    - TARGET='field-all'
    - TARGET='field-json'

    - TARGET='indent-all'
    - TARGET='symbol-all'

script: ./test.sh
...
