---
language: vim
dist: trusty
sudo: required

before_install:
  - git clone https://github.com/junegunn/vader.vim.git ~/.vim/plugged/vader.vim
  - git clone https://github.com/vim/vim
  - rbenv shell system

install:
  - >
    (cd vim ; ./configure
    --with-features=huge
    --enable-rubyinterp
    --enable-pythoninterp)
  - make -C ./vim -j4
  - sudo make -C ./vim install

before_script:
  - export PATH=/usr/local/bin:${PATH}

after_failure:
  - >
    vim --nofork
    --cmd 'ruby require "rbconfig";
    print File.join(RbConfig::CONFIG["bindir"], RbConfig::CONFIG["ruby_install_name"])'
    --cmd 'q' 2>&1 >/dev/null | grep -v 'Vim: Warning'
script:
  - vim -u test/vimrc-test -c 'Vader! test/*.vader' > /dev/null
...
