#!/usr/bin/env bash

vim -e -u NONE -c ':set t_ti= t_te= nomore' -c 'pwd'
vim -Es -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/alias-spec.vader'
vim -Es -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/expression-general-spec.vader'
vim -Es -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/expression-whitespace-spec.vader'
vim -Es -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/expression-nested-spec.vader'
vim -Es -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/expression-multiline-trailing-spec.vader'
vim -Es -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/expression-multiline-leading-spec.vader'
vim -Es -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/expression-multiline-indented-spec.vader'
vim -Es -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/field-short-if-spec.vader'
vim -Es -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/field-short-af-spec.vader'
vim -Es -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/field-trailing-if-spec.vader'
vim -Es -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/field-trailing-af-spec.vader'
vim -Es -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/field-indented-if-spec.vader'
vim -Es -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/field-indented-af-spec.vader'
vim -Es -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/field-leading-if-spec.vader'
vim -Es -u 'test/vimrc-test.vim' -c 'Vader! test/bracket/field-leading-af-spec.vader'
vim -Es -u 'test/vimrc-test.vim' -c 'Vader! test/other/indent-spec.vader'
vim -Es -u 'test/vimrc-test.vim' -c 'Vader! test/other/symbol-spec.vader'
